version: 0.2
 
phases:
install: 
    commands:
      - echo CODEBUILD_SRC_DIR - $CODEBUILD_SRC_DIR
      - echo GOPATH - $GOPATH
      - echo GOROOT - $GOROOT
  build:
    commands:
      - go get ./...
      - go get github.com/JuanValero25/EasyDynamoDB
      - go get github.com/aws/aws-lambda-go/lambda
      - go build main.go
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - main
