version: 0.2
 
phases:
install: 
    commands:
      - go get github.com/JuanValero25/EasyDynamoDB
      - go get github.com/aws/aws-lambda-go/lambda
  build:
    commands:
      - GOOS=linux GOARCH=amd64 go build -o main main.go
      - zip main.zip main
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - main
