version: 0.2
 install: 
    commands:
      - go get github.com/JuanValero25/EasyDynamoDB/...
      - go get github.com/aws/aws-lambda-go/lambda
phases:
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Go code...
      - go build -o main main.go
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - main
