version: 0.1
            
phases:

  install: 
    commands:
      - go get -u github.com/JuanValero25/EasyDynamoDB/...
      - go get -u github.com/aws/aws-lambda-go/lambda

  pre_build: 
    commands:


  build:
    commands:

      # Build our application
      - go build -o main

artifacts:
  files:
    - main
