version: 0.1
            
phases:

  install: 
    commands:
      - go get -u github.com/JuanValero25/EasyDynamoDB/...
      - go get -u github.com/aws/aws-lambda-go/lambda

  pre_build: 
    commands:
      echo  CODEBUILD_GIT_AUTHOR = $CODEBUILD_GIT_AUTHOR
      echo  CODEBUILD_GIT_AUTHOR_EMAIL = $CODEBUILD_GIT_AUTHOR_EMAIL
      echo  CODEBUILD_GIT_BRANCH = $CODEBUILD_GIT_BRANCH
      echo  CODEBUILD_GIT_COMMIT = $CODEBUILD_GIT_COMMIT
      echo  CODEBUILD_GIT_MESSAGE = $CODEBUILD_GIT_MESSAGE

  build:
    commands:

      # Build our application
      - go build -o main

artifacts:
  files:
    - main
    - lambdaProperties.yaml
