version: 0.1
            
phases:

  install: 
    commands:
      - go get -u github.com/golang/lint/golint
      - go get -u github.com/JuanValero25/EasyDynamoDB
      - go get -u github.com/aws/aws-lambda-go/lambda

  pre_build: 
    commands:

      # Ensure code passes all lint tests
      - golint -set_exit_status

      # Run all tests included with our application
      - go test

  build:
    commands:

      # Build our application
      - go build -o app

artifacts:
  files:
    - app
