package main

import (
	"github.com/aws/aws-lambda-go/lambda"
	"context"
	"github.com/JuanValero25/EasyDynamoDB/easydynamoclient"
	"github.com/JuanValero25/EasyDynamoDB/lambdaconfig"
)

type Account struct{
	AccountId string `AutoGenerated:"true"`
	InterestingData string
	PhoneNumber string
}

func main(){
	lambda.Start(HandleRequest)
}

func HandleRequest(ctx context.Context, obj lambdaconfig.TableInfo) {
	easydynamoclient.New().Save(obj)

}