package main

import (
	"github.com/aws/aws-lambda-go/lambda"
	"context"
	"github.com/JuanValero25/EasyDynamoDB/easydynamoclient"
	"github.com/JuanValero25/EasyDynamoDB/lambdaconfig"
)
//this the struct for account
type Account struct{
	AccountID string `AutoGenerated:"true"`
	InterestingData string
	PhoneNumber string
}

func main(){
	lambda.Start(HandleRequest)
}
//this is the handler
func HandleRequest(ctx context.Context, obj lambdaconfig.TableInfo) {
	easydynamoclient.New().Save(obj)

}
