package main

import (
	"github.com/aws/aws-lambda-go/lambda"
	"context"
	"github.com/JuanValero25/EasyDynamoDB/easydynamoclient"
)

type Account struct{
	AccountId string `AutoGenerated:"true"`
	InterestingData string
	PhoneNumber string
}

func (acc Account) TableName() string{
	return "Account"
}

func main(){
	lambda.Start(HandleRequest)
}

func HandleRequest(ctx context.Context, obj Account) {
	easydynamoclient.New().Save(&obj)
}
